name: Validate application

description: |
  This composite action validates the project:
  - installs dependencies
  - runs lint
  - runs type checks
  - runs tests
  - validates version

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Change working directory
      run: cd frontend
      shell: bash
      
    - name: Install dependencies
      uses: Admin-EasyFix/github-actions/actions/npm/install@main

    - name: Run ESLint
      uses: Admin-EasyFix/github-actions/actions/npm/run-eslint@main
      
    - name: Run type check
      uses: Admin-EasyFix/github-actions/actions/npm/run-type-check@main

    - name: Run tests
      uses: Admin-EasyFix/github-actions/actions/npm/run-tests@main

    - name: Ensure version is updated
      uses: Admin-EasyFix/github-actions/actions/npm/validate-version@main
