services:
  db:
    image: postgres:15
    container_name: agon-db
    restart: always
    environment:
      POSTGRES_USER: "agon"
      POSTGRES_PASSWORD: "agon"
      POSTGRES_DB: "agon"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: