services:
  postgres_dev:
    image: postgres:14-alpine
    container_name: agon_postgres_dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agon_dev
    ports:
      - '5432:5432'
    volumes:
      - ./dev-db-data:/var/lib/postgresql/data