name: Validate application

description: |
  This composite action validates the project:
  - installs dependencies
  - runs lint
  - runs type checks
  - runs tests

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
      
    - name: Install dependencies
      uses: Admin-EasyFix/github-actions/actions/npm/install@main
      with:
        working-directory: frontend

    - name: Run ESLint
      uses: Admin-EasyFix/github-actions/actions/npm/lint@main
      with:
        working-directory: frontend
      
    - name: Run type check
      uses: Admin-EasyFix/github-actions/actions/npm/type-check@main
      with:
        working-directory: frontend

    - name: Run tests
      uses: Admin-EasyFix/github-actions/actions/npm/run-tests@main
      with:
        working-directory: frontend
