name: Validate pull request version

description: This workflow validates that the version in package.json has been updated in the pull request.

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-pull-request:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Validate application
      uses: ./.github/actions/validate-version